# Generated by Django 5.1.7 on 2025-03-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='Descrição',
            new_name='Descricao',
        ),
    ]
